### ISSUE TITLE
Move Partnership Playbook Link

### ISSUE THREAD

**Issue by wslack** [18F/intake#23]
I think it's a little user unfriendly to link off to the partnership playbook in the middle of the menu without being clear you are leaving intake-land. Thoughts @awfrancisco or @StephaniePlageman?

**Comment by awfrancisco** [comment]
Yeah. I think the nav will need some work, but wanted to wait until all the new pages are up. Maybe hold this issue until we've got all the new content loaded in? 

Or do you want to designate the playbook as an external link?

**Comment by wslack** [comment]
I'm fine waiting until the rest is updated.

**Comment by wslack** [comment]
addressed by https://github.com/18F/intake/pull/38
