### ISSUE TITLE
Past Work images aren't sized right on low-width pages

### ISSUE THREAD

**Issue by wslack** [18F/intake#27]
https://github.com/18F/pages/issues/50 is causing https://pages.18f.gov/intake/past-work/ to display bad on low-width pages (though it doesn't look horrible on iPhone)

**Comment by wslack** [comment]
@juliaelman, not sure if you saw this, but something is still afoot here, my guess involving a fix with 

.main-content {
  img {  
    width: 100%;

  }
}

**Comment by juliasolorzano** [comment]
@wslack that is actually the property that makes it resize to the current width. You can now see this working on staging: https://pages-staging.18f.gov/intake/past-work/

Closing this issue! :boom:

**Comment by wslack** [comment]
Yep! I checked and that fixed it! :+1:
