### ISSUE TITLE
Broken link from intake/infrastructure to cloud.gov

### ISSUE THREAD

**Issue by peterbenmeyer** [18F/intake#54]
https://pages.18f.gov/intake/business-lines/infrastructure/ has a hyperlink to https://pages.18f.gov/intake/business-lines/infrastructure/cloud.gov but there's nothing at that URL.  

Possibly a link to https://cloud.gov/ was intended.

**Comment by wslack** [comment]
This is now fixed and tested. Thank you @peterbenmeyer!
