### ISSUE TITLE
Information on Authorizing Official Designees

### ISSUE THREAD

**Issue by NoahKunin** [18F/intake#57]
Don't know where to pull request this just yet. Feedback welcome.

---

The role of Authorizing Official (AO) Designated Representative is important to keep work in an agile project flowing. While these designees **cannot accept risk** they can make decisions more quickly then a full AO, and ensure the ATO does not have to through multiple cycles of review.

18F **strongly recommends** that an AO Designated Representative is established before a project starts, or as soon as possible. This is extremely important when 18F will not be offering the finished system in a Software as a Service (SaaS) model, but will instead be transferring the system to the Requesting Agency to launch into live production.

The role is defined in [**NIST Special Publication 800-37:** _Guide for Applying the Risk Management Framework to Federal Information Systems_](http://csrc.nist.gov/publications/nistpubs/800-37-rev1/sp800-37-rev1-final.pdf) in ￼Appendix D, Page D-4:

> **D.7 AUTHORIZING OFFICIAL DESIGNATED REPRESENTATIVE**
> 
> The authorizing official designated representative is an organizational official that acts on behalf of an authorizing official to coordinate and conduct the required day-to-day activities associated with the security authorization process. Authorizing official designated representatives can be empowered by authorizing officials to make certain decisions with regard to the planning and resourcing of the security authorization process, approval of the security plan, approval and monitoring the implementation of plans of action and milestones, and the assessment and/or determination of risk. 
> 
> The designated representative may also be called upon to prepare the final authorization package, obtain the authorizing official’s signature on the authorization decision document, and transmit the authorization package to appropriate organizational officials. The only activity that cannot be delegated to the designated representative by the authorizing official is the authorization decision and signing of the associated authorization decision document (i.e., the acceptance of risk to organizational operations and assets, individuals, other organizations, and the Nation).

**Comment by wslack** [comment]
(will likely not go here) (EDIT 2/16/16 - nvm)

**Comment by leahbannon** [comment]
- Is this a person on the 18F team or the client partner team? 
- what does "accepting risk" mean?
- maybe reordering this sentence would be more clear: "This is extremely important when 18F will be transferring the system to the Requesting Agency to launch into live production (not when 18F is offering the finished system in a Software as a Service (SaaS) model, such as cloud.gov)."
- I suggest moving the 1st sentence of the 2nd paragraph to the beginning. Starting with the action required helps me better understand the context for why I'm reading something.
- Recommend changing "18F strongly recommends that an AO Designated Representative is established" to "18F strongly recommends establishing an AO Designated Representative"
- Change "risk they can make decisions more quickly then a full AO" to "risk, they can make decisions more quickly than a full AO"

**Comment by wslack** [comment]
Is this going to be in the product guide, here, or in the before-you-ship repo?

Right now, my assumption is the product guide is internal facing and this site is external facing. Thoughts? @NoahKunin?

**Comment by afeld** [comment]
> Is this going to be in the product guide, here, or in the before-you-ship repo?

I think we figured this site would make the most sense, because that decision would/should get made before a product manager/team gets involved.

https://github.com/18F/before-you-ship/issues/65#issuecomment-173832644

**Comment by wslack** [comment]
:+1:

**Comment by wslack** [comment]
Closing this as this repo is now deprecated
