### ISSUE TITLE
Clarify Start Dates

### ISSUE THREAD

**Issue by wslack** [18F/intake#67]
- Should be clear that we are not obligated to begin work "as soon as the ink is dry" on an agreement
-  Start dates are more about setting the project up for success, as opposed to getting started as soon as possible.

Per https://github.com/18F/partnership-playbook/issues/19

**Comment by wslack** [comment]
I think we can add a bullet point to https://pages.18f.gov/intake/intake-process/ - thoughts @ominina?

**Comment by batemapf** [comment]
@wslack thanks! is this external facing?

**Comment by wslack** [comment]
@batemapf yes. At some point, this page will be linked from the homepage or featured in a blog post.
